### ISSUE TITLE
[Feature]: Implement questions engine for Artisan

### ISSUE THREAD

**Issue by jlenon7** [AthennaIO/Artisan#61]
### 🚀 Feature Proposal

The developer should be able to make questions and get the answer in commands. Tip: [Inquirer](https://www.npmjs.com/package/inquirer)

### Motivation

With question, we should be able to get more data from what the user wants to do in that respective command.

### Example

Example using a make:crud Artisan command:

```shell
node artisan make:crud

> What will be the name of your CRUD?
User

> Do you want to add a new column?
yes

> What is the name of your column?
name

> What is the lenght of your column?
255

> What is the default value of your column? (set "null" for null value)
null

> Select your column options:

[ ] nullable
[ ] unique
[ ] hidden
[ ] primary
```

**Comment by RobsonTrasel** [comment]
Is there a library that you recommend that does this job or just the Inquirer?

**Comment by jlenon7** [comment]
There might be other libraries to do that, but I think that Inquirer has a good API. We can integrate Inquirer easily in [Command](https://github.com/AthennaIO/Artisan/blob/develop/src/Commands/Command.js) class and implement some methods to retrieve data in different ways from the user:

- `ask` Just get the user input
- `secret` Same as `ask` method, but the user input will not appear for him
- `confirm` Ask the user if he wants to proceed and return `true` or `false`
- `checkbox` Create a list of options to the user where only one can be selected and return the only one selected
- `listCheckbox` Create a list of options to the user where more than one can be selected and return the selected ones as array

```js
import { Artisan, Command } from '@athenna/artisan'

export class List extends Command {
  /**
   * The name and signature of the console command.
   *
   * @return {string}
   */
  get signature() {
    return 'example'
  }

  /**
   * The console command description.
   *
   * @return {string}
   */
  get description() {
    return 'Command description.'
  }

  /**
   * Execute the console command.
   *
   * @return {Promise<void>}
   */
  async handle() {
    const options = ['1', '2', '3']

    const username = await this.ask('What is your username?') // 'Lenon'
    const password = await this.secret('What is your password?') // '1234'
    const isConfirmed = await this.confirm('Do you wish to proceed?') // true
    const number = await this.checkbox('Select one number:', options) // '1'
    const numbers = await this.listCheckbox('Select numbers:', options) // ['1', '3']
  }
}
```

These methods could be implemented using the [Inquirer question object](https://www.npmjs.com/package/inquirer#question) and the `prompt` method.
